name: Deploy baton user api

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    environment: deploy
    strategy:
      matrix:
        python-version: [3.9]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Setting .env.prod for each apps
        run: |
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env.prod
          echo "DATABASES_NAME=${{ secrets.DATABASES_NAME }}" >> .env.prod
          echo "DATABASES_USER=${{ secrets.DATABASES_USER }}" >> .env.prod
          echo "DATABASES_PASSWORD=${{ secrets.DATABASES_PASSWORD }}" >> .env.prod
          echo "DATABASES_HOST=${{ secrets.DATABASES_HOST }}" >> .env.prod
          echo "DATABASES_PORT=${{ secrets.DATABASES_PORT }}" >> .env.prod
          echo "KAKAO_REST_API_KEY=${{ secrets.KAKAO_REST_API_KEY }}" >> .env.prod
          cat .env.prod

      - name: Setting .env for docker-compose
        run: |
          echo "ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}" >> .env
          echo "IMAGE_TAG=${{ github.sha }}" >> .env
          cat .env

      - name: Build and push image to Amazon ECR
        run: |
          docker-compose -f docker-compose.prod.yml push
#          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
#          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest .

